# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetid', models.CharField(max_length=100, verbose_name='\u30a2\u30bb\u30c3\u30c8ID\u540d')),
                ('txid', models.CharField(max_length=100, verbose_name='\u30c8\u30e9\u30f3\u30b6\u30af\u30b7\u30e7\u30f3ID\u540d')),
                ('assetamount', models.CharField(help_text='\u30a2\u30bb\u30c3\u30c8\u306e\u767a\u884c\u6570\u91cf\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044', max_length=40, verbose_name='\u767a\u884c\u6570\u91cf')),
                ('tokenamount', models.CharField(help_text='\u518d\u767a\u884c\u8981\u5426\uff081:\u518d\u767a\u884c\u6709\u30010:\u518d\u767a\u884c\u7121\uff09\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002', max_length=1, verbose_name='\u518d\u767a\u884c\u8981\u5426\uff081:\u6709\u30010:\u7121\uff09')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u767b\u9332\u65e5\u6642')),
            ],
        ),
        migrations.CreateModel(
            name='SendAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetid', models.CharField(max_length=100, verbose_name='\u30a2\u30bb\u30c3\u30c8ID\u540d')),
                ('txid', models.CharField(max_length=100, verbose_name='\u30c8\u30e9\u30f3\u30b6\u30af\u30b7\u30e7\u30f3ID\u540d')),
                ('addresstosend', models.CharField(max_length=100, verbose_name='\u9001\u91d1\u5148\u30a2\u30c9\u30ec\u30b9')),
                ('amounttosend', models.CharField(help_text='\u30a2\u30bb\u30c3\u30c8\u306e\u9001\u91d1\u6570\u91cf\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044', max_length=40, verbose_name='\u9001\u91d1\u6570\u91cf')),
                ('balance', models.CharField(max_length=40, verbose_name='\u30a2\u30bb\u30c3\u30c8\u6b8b\u9ad8')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='\u9001\u91d1\u65e5\u6642')),
            ],
        ),
    ]
