# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_issueasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueasset',
            name='tokenamount',
        ),
    ]
